# Generated by Django 5.1 on 2024-09-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_pruduto_produto_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
