# Generated by Django 5.1 on 2024-09-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='request',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='price',
            new_name='preço',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='price_promotional',
            new_name='preço_promocional',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='product',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='amount',
            new_name='produto_id',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='product_id',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='variation',
            new_name='variacao',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='variation_id',
            new_name='variacao_id',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='amount',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='user_pd',
            new_name='usuario',
        ),
    ]
